AllCops:
  Include:
    - 'bin/*.rb'

Metrics/LineLength:
  Max: 120

# Too fussy.
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Maybe I'll rewrite the code one day. This is not a Ruby project, this just has to work.
Style/GlobalVars:
  Enabled: false

# I like my Unicode, thankyouverymuch.
Style/AsciiComments:
  Enabled: false

# Opinions differ.
Style/BlockDelimiters:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Tab:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
  MaxLineLength: 120
Style/Next:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/WordArray:
  MinSize: 3

# RuboCop bugs cause false positives (it just hates tabs with passion).
Style/CommentIndentation:
  Enabled: false
Style/IndentAssignment:
  Enabled: false
