inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - bin/*.rb

Metrics/LineLength:
  Max: 120

# Too fussy.
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Maybe I'll rewrite the code one day. This is not a Ruby project, this just has to work.
Style/GlobalVars:
  Enabled: false

# I like my Unicode, thankyouverymuch.
Style/AsciiComments:
  Enabled: false

# Opinions differ.
Style/BlockDelimiters:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
  MaxLineLength: 120
Style/Next:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/WordArray:
  MinSize: 3

Layout/Tab:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
Layout/SpaceInsideBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf

# RuboCop bugs cause false positives (it just hates tabs with passion).
Layout/CommentIndentation:
  Enabled: false
Layout/IndentAssignment:
  Enabled: false
